// Order matters: AboutModal's physics simulation spawns tags in this exact
// array order (staggered on a fixed interval), not randomized. `promoted`
// marks the default (no variant override) larger-rendered tags — replaces
// the old hardcoded `class="level-3"` markers.
export const skills = [
  { id: 'interaction-design', label: 'Interaction Design' },
  { id: 'personas', label: 'Personas' },
  { id: 'user-experience', label: 'User Experience', promoted: true },
  { id: 'atomic-design', label: 'Atomic Design' },
  { id: 'illustration', label: 'Illustration' },
  { id: 'facilitation', label: 'Facilitation' },
  { id: 'design-tokens', label: 'Design Tokens' },
  { id: 'iconography', label: 'Iconography' },
  { id: 'figma', label: 'Figma', promoted: true },
  { id: 'stakeholder-management', label: 'Stakeholder Management' },
  { id: 'design-critique', label: 'Design Critique' },
  { id: 'inclusive-design', label: 'Inclusive Design' },
  { id: 'ai-assisted-design-workflows', label: 'AI Assisted Design Workflows' },
  { id: 'journey-mapping', label: 'Journey Mapping' },
  { id: 'microinteractions', label: 'Microinteractions' },
  { id: 'wireframing', label: 'Wireframing', promoted: true },
  { id: 'sketch', label: 'Sketch' },
  { id: 'agile-methodologies', label: 'Agile Methodologies' },
  { id: 'figjam', label: 'FigJam' },
  { id: 'color-theory', label: 'Color Theory' },
  { id: 'webflow', label: 'Webflow' },
  { id: 'mentorship', label: 'Mentorship' },
  { id: 'zeplin', label: 'Zeplin' },
  { id: 'motion-prototyping', label: 'Motion Prototyping' },
  { id: 'service-design', label: 'Service Design' },
  { id: 'responsive-web-design', label: 'Responsive Web Design', promoted: true },
  { id: 'design-operations', label: 'Design Operations' },
  { id: 'photoshop', label: 'Photoshop' },
  { id: 'user-strategy', label: 'User Strategy' },
  { id: 'art-direction', label: 'Art Direction' },
  { id: 'design-leadership', label: 'Design Leadership' },
  { id: 'interaction-animation', label: 'Interaction Animation' },
  { id: 'illustrator', label: 'Illustrator' },
  { id: 'typography', label: 'Typography' },
  { id: 'miro', label: 'Miro' },
  { id: 'protopie', label: 'ProtoPie' },
  { id: 'html-css', label: 'HTML & CSS' },
  { id: 'problem-solving', label: 'Problem Solving' },
  { id: 'principle', label: 'Principle' },
  { id: 'figma-mcp-integration', label: 'Figma MCP Integration', promoted: true },
  { id: 'design-documentation', label: 'Design Documentation' },
  { id: 'roadmapping', label: 'Roadmapping' },
  { id: 'after-effects', label: 'After Effects' },
  { id: 'accessibility', label: 'Accessibility' },
  { id: 'usability-testing', label: 'Usability Testing' },
  { id: 'cross-functional-collaboration', label: 'Cross-Functional Collaboration' },
  { id: 'mobile-web-design', label: 'Mobile Web Design', promoted: true },
  { id: 'visual-hierarchy', label: 'Visual Hierarchy' },
  { id: 'indesign', label: 'InDesign' },
  { id: 'component-libraries', label: 'Component Libraries' },
  { id: 'blender', label: 'Blender' },
  { id: 'chatgpt', label: 'ChatGPT' },
  { id: 'scalable-design', label: 'Scalable Design' },
  { id: 'data-visualization', label: 'Data Visualization' },
  { id: 'experience-design', label: 'Experience Design' },
  { id: 'design-thinking', label: 'Design Thinking' },
  { id: 'theming', label: 'Theming' },
  { id: 'framer', label: 'Framer' },
  { id: 'invision', label: 'InVision' },
  { id: 'adobe-creative-suite', label: 'Adobe Creative Suite' },
  { id: 'product-strategy', label: 'Product Strategy' },
  { id: 'javascript', label: 'JavaScript' },
  { id: 'gemini', label: 'Gemini' },
  { id: 'user-research', label: 'User Research' },
  { id: 'digital-product-design', label: 'Digital Product Design', promoted: true },
  { id: 'workshops', label: 'Workshops' },
  { id: 'graphic-design', label: 'Graphic Design' },
  { id: 'motion-graphics', label: 'Motion Graphics' },
  { id: 'visual-design', label: 'Visual Design' },
  { id: 'animate', label: 'Animate' },
  { id: 'frontend-development', label: 'Frontend Development' },
  { id: 'claude-design', label: 'Claude Design' },
  { id: 'simplification', label: 'Simplification' },
  { id: 'user-interface', label: 'User Interface', promoted: true },
  { id: 'layout', label: 'Layout' },
  { id: 'information-architecture', label: 'Information Architecture' },
  { id: 'design-systems', label: 'Design Systems', promoted: true },
  { id: 'prototyping', label: 'Prototyping' },
  { id: 'user-centered-design', label: 'User-Centered Design' },
  { id: 'storybook', label: 'Storybook' },
]
