export const blocks = [
  {
    id: 'media-home-side-by-side',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/home-side-by-side.png',
    alt: 'Before-and-after comparison of the EverlyWell homepage',
    spaceBottom: true,
  },
  {
    id: 'intro-paragraph',
    type: 'paragraph',
    text: "EverlyWell sells at-home lab testing kits for things such as thyroid, vitamins, STD, and food sensitivities. After a user collects their sample (the method which varies from test to test) and mails it in, EverlyWell's lab partners process the sample and help the end user make sense of the results.",
  },
  {
    id: 'context-paragraph',
    type: 'paragraph',
    text: 'When I joined, EverlyWell had just raised its series A and had a staff of about 25 people. I stayed 18 months, and during that time it raised its series B, launched two major versions of its results platform, tripled in staff, and began offering several additional tests.',
  },
  { id: 'heading-results-platform', type: 'heading', level: 2, text: 'Results Platform Redesign, Content, & Design System' },
  {
    id: 'content-system-paragraph',
    type: 'paragraph',
    text: "When I joined, EverlyWell's results platform had a one-size-fits-all approach to 30 different tests, and we consistently heard that users' results didn't feel very personalized or actionable. Using low fidelity wireframes, I created a modular content system to outline the different blocks of content we'd show, and when. For example, if a user had taken the same test six times and their latest results were normal, we wouldn't show the same content as a brand new user who had abnormal results. This was a page from a document intended to get buy-in from stakeholders on what these blocks were, what order we'd show them, and in what phase we'd roll them out.",
  },
  {
    id: 'media-content-blocks',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/ContentBlocks.png',
    alt: 'Stakeholder document outlining modular content blocks for personalized results',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'tone-balance-paragraph',
    type: 'paragraph',
    text: "We were also working to make the experience feel more dynamic and engaging, but we had to strike the right balance with this because some folks may have been getting bad news. Anyone who had biomarkers in dangerous zones would have received a phone call from one of EverlyWell's medical staff, but still, an overly cheerful animation doesn't land well with a positive STD result.",
  },
  {
    id: 'media-intro-video',
    type: 'media',
    kind: 'video',
    src: '/assets/img/everlywell/intro.mp4',
    alt: 'Introductory animation for the EverlyWell results experience',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'design-system-paragraph',
    type: 'paragraph',
    text: "A proper design system hadn't really been established, so we created one in parallel of designing the UX and UI for the new results platform.",
  },
  {
    id: 'media-ui-kit',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/UIKit.png',
    alt: 'EverlyWell UI kit and design system components',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'color-fragmentation-paragraph',
    type: 'paragraph',
    text: "EverlyWell had a lot of fragmentation when it came to color. There were two or three blues used for button colors, and three or four different greens used throughout the site. To make matters worse, one of our frontend engineers was colorblind, and it was really difficult for him to notice the differences. Additionally the entire company was wanting to become more ADA compliant, and we really didn't have any internal guidelines on how that would translate to our work. I followed Lyft's lead and used their color tool to create a systematic color scheme. Black text was compliant on the 6 inner rings, and white text was compliant on the 6 outer rings. We didn't use more than a handful of the colors, but it gave us room to grow if we needed. It was much easier to tell the devs to use Blue 4 instead of The same one we use for button colors. Plus since all the colors were variables in the code, it paved the way to more smoothly roll out future branding.",
  },
  {
    id: 'media-ada-color-wheel',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/ADA-Color-Wheel.svg',
    alt: 'ADA-compliant color wheel created for the EverlyWell design system',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'biomarker-cards-paragraph',
    type: 'paragraph',
    text: "There were a lot of variations on how we'd show the biomarker cards. Some were simple You have this or don't cards while others showed several ranges a person's results might fall under, each with a lab-provided label we legally had to use. So part of the job was making sure these were all intuitive, looked like they came from the same place, and were flexible enough to include all the content they might contain.",
  },
  {
    id: 'media-tiles',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/tiles.png',
    alt: 'Biomarker result card variations',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'credits-paragraph',
    type: 'paragraph',
    text: 'There was a running joke that time spent at EverlyWell was like dog years, because everyone did a lot in a small amount of time. EverlyWell\'s branding was purchased through Fiverr, and the marketing site when I arrived had been designed by Funsize. A lot of talented people helped create the 2019 design for the results platform, including <a href="https://www.anna-ho.com/" target="_blank">Anna Ho</a>, <a href="https://www.linkedin.com/in/willfikes/" target="_blank">Will Fikes</a>, and <a href="https://www.linkedin.com/in/ericalanboggs/" target="_blank">Eric Boggs</a>.',
  },
  {
    id: 'media-dashboard-side-by-side',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/dashboard-side-by-side.png',
    alt: 'Before-and-after comparison of the EverlyWell dashboard',
  },
  { id: 'heading-humana-partnership', type: 'heading', level: 2, text: 'Humana Partnership' },
  {
    id: 'humana-intro-paragraph',
    type: 'paragraph',
    text: "EverlyWell's first big partnership was with health insurance and wellness giant Humana to provide HbA1c and Colorectal Cancer screening tests to eligible seniors through their Humana healthcare plans. Since EverlyWell's platform didn't follow any kind of accessibility guidelines, and Humana wanted a co-branded experience, we opted to do a separate microsite to handle the entire process. The results were still shown on the primary EverlyWell platform, and we updated it to allow for co-branding which we knew we wanted to enable in the future and wasn't a very big lift.",
  },
  {
    id: 'media-humana-home',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/humana-home.png',
    alt: 'Co-branded Humana microsite homepage',
    spaceBottom: true,
  },
  {
    id: 'caregiver-paragraph',
    type: 'paragraph',
    text: 'One interesting thing about the flows was that a caregiver could be going through them on behalf of the Humana member, and different verification needed to happen if that were the case.',
  },
  {
    id: 'media-humana-verification',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/humana-verification.png',
    alt: 'Caregiver verification flow for the Humana partnership',
    spaceBottom: true,
  },
  {
    id: 'humana-outcome-paragraph',
    type: 'paragraph',
    text: "The Humana collaboration was a huge success. I don't have numbers on how many tests were registered or how Humana benefited, but this was the first in EverlyWell's step toward working with enterprise customers and larger providers. It also paved the way for further whitelabeling of the product pages, and increased the team's understanding of what it took to make a site with AAA WCAG compliance in mind.",
  },
  { id: 'heading-science-page', type: 'heading', level: 2, text: 'Science Page Redesign' },
  {
    id: 'science-page-paragraph',
    type: 'paragraph',
    text: "When the 2019 Theranos documentary was about to be released on HBO, EverlyWell's leaders were working hard to close series B funding. The website had only cursory information about the science behind EverlyWell's tests, and it wasn't easy to find. With a turnaround of only a few weeks, we planned, designed, wrangled content for, and published a brand new science section prominently featured in the main navigation.",
  },
  {
    id: 'media-science-page',
    type: 'media',
    kind: 'image',
    src: '/assets/img/everlywell/SciencePage.jpg',
    alt: 'Redesigned science section of the EverlyWell site',
    spaceTop: true,
    spaceBottom: true,
  },
  { id: 'heading-pdp-redesign', type: 'heading', level: 2, text: 'Product Page Redesign' },
  {
    id: 'media-pdp-video',
    type: 'media',
    kind: 'video',
    src: '/assets/img/everlywell/pdp-side-by-side.mp4',
    alt: 'Before-and-after comparison video of the EverlyWell product detail page',
    spaceBottom: true,
  },
  {
    id: 'pdp-challenge-paragraph',
    type: 'paragraph',
    text: "Taking on EverlyWell's product detail page redesign was an interesting challenge – their existing PDPs were functional, but still included the As seen on Shark Tank! verbiage and contained 6 tabs of heavy text details describing the tests and what they measured. The team initially approached me to refresh the page, but after digging into their analytics and customer feedback, it became clear we needed to do more than just give it a new coat of paint. There was a disconnect between the friendly, approachable brand EverlyWell had built and the somewhat sterile experience of actually shopping for their products.",
  },
  {
    id: 'pdp-process-paragraph',
    type: 'paragraph',
    text: 'I worked closely with the marketing team to understand what messaging resonated most with customers, and with the product team to identify where people were getting stuck in the purchase flow. We did some guerilla user testing by just asking strangers to look at the site on an iPad, just to get some anecdotal qualitative data on it. The biggest challenge was ensuring it felt medically credible while still having an element of novelty to it, because the majority of the traffic that would be driven to these pages was from Facebook and Instagram.',
  },
  {
    id: 'pdp-outcome-paragraph',
    type: 'paragraph',
    text: 'The redesigned PDP brought their brand personality forward while strategically organizing information to address common questions and concerns at each stage of the decision process. We gave more prominence to their scientific validation, simplified the explanation of how the tests work, and made the benefits more tangible through improved visualization. When we launched the new design, we saw an immediate uptick in conversion rates, which validated our approach and gave us good footing to expand the redesign to other parts of their site.',
  },
]
