export const blocks = [
  {
    id: 'media-design-system',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/design-system.png',
    alt: 'Hallmark design system components',
    spaceBottom: true,
  },
  {
    id: 'intro-paragraph',
    type: 'paragraph',
    text: 'People close to me can tell you that I can be kind of a schmaltzy guy, and part of the reason I went to an agency was so I could work on bigger name projects. So when I was interviewing with T3 and learned my first client would be Hallmark, you could imagine my excitement! On my second day of work, I flew to their corporate HQ in Kansas City to meet the team and participate in workshops where I learned about the projects and who we were building them for.',
  },
  {
    id: 'gallery-treatments',
    type: 'gallery',
    columns: 3,
    spaceTop: true,
    spaceBottom: true,
    items: [
      { src: '/assets/img/hallmark/treatment-a-edit.gif', alt: 'Visual treatment exploration A for the new Hallmark site' },
      { src: '/assets/img/hallmark/treatment-b-edit.gif', alt: 'Visual treatment exploration B for the new Hallmark site' },
      { src: '/assets/img/hallmark/treatment-c-edit.gif', alt: 'Visual treatment exploration C for the new Hallmark site' },
      { src: '/assets/img/hallmark/treatment-d-edit.gif', alt: 'Visual treatment exploration D for the new Hallmark site' },
      { src: '/assets/img/hallmark/treatment-e-edit.gif', alt: 'Visual treatment exploration E for the new Hallmark site' },
      { src: '/assets/img/hallmark/treatment-f.gif', alt: 'Visual treatment exploration F for the new Hallmark site' },
    ],
  },
  {
    id: 'engagement-paragraph',
    type: 'paragraph',
    text: "We were designing what would eventually become the new Hallmark Cards site. Our engagement lasted over a year, so I was involved in a variety of initiatives coordinating with other designers on laying the groundwork for a new design system; designing the main navigation; collaborating with Hallmark's internal stakeholders on how the new site's registration would work with Hallmark's Crown Rewards program; and designing the product details page (PDP) to name the big ones.",
  },
  {
    id: 'media-scroll-test-video',
    type: 'media',
    kind: 'video',
    src: '/assets/img/hallmark/simul-scroll-test.mp4',
    alt: 'Simultaneous scroll interaction test for the Hallmark site',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-pdp-side-by-side',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/pdp-side-by-side.png',
    alt: 'Before-and-after comparison of the Hallmark product detail page',
    spaceBottom: true,
  },
  {
    id: 'pdp-paragraph',
    type: 'paragraph',
    text: 'This was my first time designing a PDP for a company as big as Hallmark, and I learned a lot about order fulfillment and the different ways a product needed to be represented. Designing the find-a-store feature was also a cool challenge with a lot of edge cases to account for.',
  },
  {
    id: 'media-find-a-store-behavior',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/Find-a-Store-Behavior.png',
    alt: 'Behavior diagram for the Hallmark find-a-store feature',
    spaceBottom: true,
  },
  {
    id: 'media-find-a-store-states',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/Find-a-Store-States.png',
    alt: 'UI states for the Hallmark find-a-store feature',
    spaceBottom: true,
  },
  {
    id: 'media-address-lockups',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/HM-Address-Lockups.png',
    alt: 'Address lockup design variations for Hallmark',
    spaceBottom: true,
  },
  {
    id: 'media-login-flow',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/login-flow.png',
    alt: 'Hallmark account login flow',
    spaceBottom: true,
  },
  {
    id: 'signup-flow-paragraph',
    type: 'paragraph',
    text: "Flowchart detailing sign up behavior. Hallmark's leadership wanted user registration to automatically assign a rewards account to any new user signing up. But because customers could enroll in the rewards program at a physical Hallmark store without providing an email address, we wanted to afford the ability to link an existing rewards program account during account registration. Similar functionality existed in the account area, but we knew resolving it here would reduce support call volume to Hallmark.",
  },
  {
    id: 'custom-cards-paragraph',
    type: 'paragraph',
    text: 'One of the coolest features I helped with was a means for folks to create custom cards. This was a brand new feature for Hallmark, so our team was able to really have fun with it.',
  },
  {
    id: 'media-custom-card',
    type: 'media',
    kind: 'image',
    src: '/assets/img/hallmark/POD-Non-Color-Sku-Inside-Right.png',
    alt: 'Custom card design showing a non-color SKU on the inside right panel',
    modifier: 'tall',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'outcome-paragraph',
    type: 'paragraph',
    text: "Hallmark saw an enormous increase in card sales after the launch of this new site. Although it was during the 2020 COVID-19 pandemic and folks wanting to reach out to each other from afar was no doubt partly responsible, I know our work contributed to this and at the end of the day helped brighten some people's days. What more can you ask for? I've stayed in touch with some of the people from this era and hope I get to work with them again sometime.",
  },
]
