export const blocks = [
  {
    id: 'media-message-sent',
    type: 'media',
    kind: 'image',
    src: '/assets/img/workstep/inform/inform-message-sent.png',
    alt: 'Confirmation screen after an Inform broadcast message is sent',
    wide: true,
    spaceBottom: true,
  },
  {
    id: 'intro-paragraph',
    type: 'paragraph',
    text: "Frontline workers in warehouses and supply chains are notoriously hard to reach. They don't sit at desks. Many don't have company email. When something important happens, a facility closure, a policy change, a safety update, the message often doesn't get there in time, or at all. WorkStep already facilitated anonymous conversations between employees and HR, but only when an employee initiated one by leaving a comment on a survey. Employers had no way to start that conversation themselves. Inform was built to close that gap: a broadcast messaging tool that lets employers reach specific groups of workers directly, without ever exposing individual identities to the sender.",
  },
  {
    id: 'metrics-launch',
    type: 'metrics',
    spaceTop: true,
    spaceBottom: true,
    items: [
      { value: '7K', label: 'messages sent by 90 companies in 3 years' },
      { value: '4.7M', label: 'messages delivered to 400K+ recipients in 3 years' },
      { value: '50K', label: 'message reactions in a year' },
    ],
  },
  { id: 'heading-problem', type: 'heading', level: 2, text: 'The problem worth solving' },
  {
    id: 'problem-paragraph',
    type: 'paragraph',
    text: "The interesting part of this project was more organizational than technical. Employers needed enough precision to send the right message to the right people, but giving them a list of names and checkboxes would have undermined the trust WorkStep's anonymity model worked so hard to preserve. So the feature had to strike the right balance between allowing employers specificity without giving it the ability to invade people's privacy, and it was on us to find the right way to accommodate it with the right balance.",
  },
  { id: 'heading-segment-builder', type: 'heading', level: 2, text: 'Building the segment builder' },
  {
    id: 'segment-intro-paragraph',
    type: 'paragraph',
    text: "The heart of Inform is a query interface that lets employers define a recipient list through stacked attribute rules (such as role, division, location, and tenure) without ever seeing who the attributes specifically match. The live count at the top of the panel quietly signals both that the list changes dynamically, but also helps signal to the employer the size the audience for the message will be and reassures them it isn't just going into an empty void.",
  },
  {
    id: 'media-query-builder',
    type: 'media',
    kind: 'image',
    src: '/assets/img/workstep/inform/inform-query-builder-3.png',
    alt: "Inform's segment builder with stacked attribute rules defining a recipient list",
  },
  {
    id: 'conditional-logic-paragraph',
    type: 'paragraph',
    text: 'The filter rows follow conditional logic. Selecting "Unfavorable feedback" surfaces a topic dropdown: Tools, Pay, Safety, Manager Relationship. Selecting "Employee Tenure" replaces it with a numeric range input instead. The first choice shapes what comes after. When it works well, this kind of branching interaction is completely invisible. You just feel like the interface understood what you were trying to do.',
  },
  {
    id: 'control-placement-paragraph',
    type: 'paragraph',
    text: "I tried different placements for the add and remove controls before landing on left-aligned icons that form a consistent vertical axis down the panel. This bent a design system convention. Buttons with icons don't normally carry that much space between the icon and the label, but it felt more important to visually align the label with the first field of each row than to follow the rule for its own sake.",
  },
  {
    id: 'segment-name-paragraph',
    type: 'paragraph',
    text: 'The segment name field, labeled "Your employees will not see this," is a small detail that I think mattered a lot. These aren\'t abstract query objects, but groups of real people that managers already think about by name. The label is just a quiet acknowledgment of that.',
  },
  { id: 'heading-reviewing-impact', type: 'heading', level: 2, text: 'Reviewing impact' },
  {
    id: 'reporting-need-paragraph',
    type: 'paragraph',
    text: 'An easy trap to fall into with a one-way communication tool like this is for it to feel like the message is going into a black hole and not seen by anyone. So to mitigate this, we opted to give a report of how many people were sent the message, via which channels, and what the open rate was like. Later after launch, we also added the ability for employees to react anonymously with an emoji which further helped reinforce that there was someone out there reading these.',
  },
  {
    id: 'gallery-graph-explorations',
    type: 'gallery',
    columns: 2,
    spaceTop: true,
    spaceBottom: true,
    items: [
      { src: '/assets/img/workstep/inform/inform-graph-1.png', alt: 'Early donut-chart exploration for the Inform reporting graph' },
      { src: '/assets/img/workstep/inform/inform-graph-2.png', alt: 'Early bar-chart exploration for the Inform reporting graph' },
      { src: '/assets/img/workstep/inform/inform-graph-3.png', alt: 'Early exploration mixing chart styles for the Inform reporting graph' },
      { src: '/assets/img/workstep/inform/inform-graph-4.png', alt: 'Another early layout exploration for the Inform reporting graph' },
      { src: '/assets/img/workstep/inform/inform-graph-5.png', alt: 'A further early layout exploration for the Inform reporting graph' },
    ],
  },
  {
    id: 'graph-choice-paragraph',
    type: 'paragraph',
    text: 'Above are some of my early explorations for our graphs on reporting send and open rates. They were fun, but all too complicated which was why we ultimately went with a simple donut.',
  },
  { id: 'heading-cutting-room-floor', type: 'heading', level: 2, text: 'The cutting room floor' },
  {
    id: 'cutting-room-intro-paragraph',
    type: 'paragraph',
    text: 'There were a few ideas we wound up leaving out for various reasons.',
  },
  {
    id: 'tenure-input-paragraph',
    type: 'paragraph',
    text: 'Within the segment builder, an early direction allowed for free-form numeric input, which I thought looked better and broke up the visual monotony of the dropdown rows. But tenure wasn\'t going to be a primary filter for most users, and even the people who did use it wouldn\'t have use cases requiring precision beyond the predetermined ranges. The PM made the call to simplify it, which I agreed to. Sometimes the right design decision is the one that matches how people actually behave, not the one that offers the most control.',
  },
  {
    id: 'media-tenure',
    type: 'media',
    kind: 'image',
    src: '/assets/img/workstep/inform/inform-tenure.png',
    alt: 'Early free-form numeric tenure filter design, later simplified to preset ranges',
  },
  {
    id: 'attachments-paragraph',
    type: 'paragraph',
    text: "Another potential feature was file attachments, which we still get requests for here and there. We determined the can of worms it would open wasn't worth the revenue increase we'd see.",
  },
  {
    id: 'gallery-attachments',
    type: 'gallery',
    columns: 2,
    spaceBottom: true,
    items: [
      { src: '/assets/img/workstep/inform/inform-attachments-a.png', alt: 'Concept for attaching a file to an Inform message' },
      { src: '/assets/img/workstep/inform/inform-attachments-errors.png', alt: 'Error states explored for a failed attachment upload' },
    ],
  },
  {
    id: 'templated-messages-paragraph',
    type: 'paragraph',
    text: 'Similar to this was the idea to allow surveys to be attached to Inform messages, templated messages, and to allow the messages to contain variables. With unlimited resouces I guarantee we would have added these things and more, but for a team this small it was time to put our pencils down and move onto the next adventure.',
  },
  { id: 'heading-impact', type: 'heading', level: 2, text: 'Impact' },
  {
    id: 'upsell-paragraph',
    type: 'paragraph',
    text: "It started as a premium upsell, but early adoption was slow. I don't think this was because the tool didn't work, but because employers weren't sure they needed it or that their employee surveying tool was a logical place to bundle a broadcast messaging tool. Folding it into the core WorkStep package and no longer offering it as an upsell changed all this. Usage expanded quickly, and the use cases turned out to be broader than anyone on our team anticipated!",
  },
  {
    id: 'use-cases-paragraph',
    type: 'paragraph',
    text: 'HR teams used it to coordinate during unexpected operational changes, warehouse managers used it to alert workers about facility closures during winter storms, someone used it to tell their team about donuts in the break room, and I live for seeing use cases like that emerge from something I made.',
  },
]
