export const blocks = [
  {
    id: 'gallery-mobile-screens',
    type: 'gallery',
    columns: 3,
    spaceBottom: true,
    items: [
      { src: '/assets/img/insitome/Neanderhtal_Insight@2x.png', alt: 'Neanderthal Insight screen' },
      { src: '/assets/img/insitome/Metabolism_Trait-Top@2x.png', alt: 'Metabolism trait screen' },
      { src: '/assets/img/insitome/Regional-Ancestry_Dashboard@2x.png', alt: 'Regional Ancestry dashboard screen' },
      { src: '/assets/img/insitome/Regional-Ancestry_Subregion@2x.png', alt: 'Regional Ancestry subregion detail screen' },
      { src: '/assets/img/insitome/Metabolism_Trait-Infographics@2x.png', alt: 'Metabolism trait infographic screen' },
    ],
  },
  {
    id: 'intro-paragraph',
    type: 'paragraph',
    text: "Insitome (pronounced insight-oam) was a company partnered with DNA testing platform, Helix. Similar to 23andMe, Helix sequenced people's DNA via mail-in saliva samples, but what made them different was providing the data to third-party app developers in a marketplace. The idea was for Helix to create a sort-of app store where people making the apps could leverage the DNA you had on file with Helix.",
  },
  {
    id: 'products-paragraph',
    type: 'paragraph',
    text: "Insitome was one of these creators, and sold separate edutainment modules that used DNA to shed light on people's various traits.",
  },
  {
    id: 'branding-credit-paragraph',
    type: 'paragraph',
    text: 'With branding and packaging created by <a href="https://elbow.com" target="_blank">Elbow</a>, and one product (Neanderthal) already in the wild, my job was to help launch two sister products, Metabolism and Regional Ancestry.',
  },
  {
    id: 'media-onboarding-flow',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/OnboardingFlow@2x.png',
    alt: 'Insitome onboarding flow diagram',
    spaceBottom: true,
  },
  {
    id: 'onboarding-problems-paragraph',
    type: 'paragraph',
    text: "But before we'd do that, there were some problems with the existing onboarding process the team wanted help with. The existing onboarding had several steps, many of which weren't skippable. Helix acting as a middleman between the apps on its marketplace and the end-user created a lot of interesting challenges from an onboarding perspective. So I put together a bevy of recommended hotfixes to make it easier for folks to activate their accounts and sign in.",
  },
  {
    id: 'media-email-stepper',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/email-stepper.png',
    alt: 'Redesigned email verification stepper for onboarding',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-icon-animations',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/icon-animations.gif',
    alt: 'Animated icon states used throughout onboarding',
    modifier: 'centered',
    spaceBottom: true,
  },
  {
    id: 'ios-web-parity-paragraph',
    type: 'paragraph',
    text: "There was a contractual obligation with Helix that created an added challenge both an iOS version and a responsive web version needed to be created in parallel. Since I'd never worked alongside an iOS developer before, I was grateful to have someone who helped me understand the nuances of layout in iOS and how they differed from web. The good news was the functionality was quite straightforward which made parity fairly easy.",
  },
  {
    id: 'media-migration',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/migration.gif',
    alt: 'Animated migration path visualization',
    spaceTop: true,
  },
  {
    id: 'media-world-map',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/WorldMap@2x.png',
    alt: 'World map showing ancestry regions and migration paths',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'maps-paragraph',
    type: 'paragraph',
    text: 'Maps were a big part of Insitome. Sitting alongside the director of science content, I acted as a pair of hands to get the regions and migration paths in the right places with the right amount of overlap. I had concepts of maps animating as the user navigated, but the scope was too big for our release timeline.',
  },
  {
    id: 'static-products-paragraph',
    type: 'paragraph',
    text: 'All three Insitome products were fairly static. The interactivity was navigating from one page to another, so the value I was able to add was helping the team understand the content hierarchy, envision how things would look, and providing as many supporting graphics as I was able.',
  },
  {
    id: 'media-responsive',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/responsive@2x.png',
    alt: 'Responsive layouts across web and iOS',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'genome-ad-paragraph',
    type: 'paragraph',
    text: "After launching the Metabolism and Regional Ancestry products, I helped create an ad for Genome magazine. Several rough concept sketches were presented, and the CEO fell in love with the idea of a decoder ring because he thought it would strike a nostalgia chord with the magazine's audience. I styled and directed the shot, retouched the photos, layed out the ad, and coordinated with Helix's legal team and Genome magazine.",
  },
  {
    id: 'media-genome-ad-sketches',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/GenomeAdSketches@2x.png',
    alt: 'Concept sketches for the Genome magazine ad',
    spaceTop: true,
  },
  {
    id: 'media-genome-ad-layout',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/Genome-Ad-Layout@2x.jpg',
    alt: 'Final layout of the Genome magazine ad featuring a decoder ring',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'sharing-intro-paragraph',
    type: 'paragraph',
    text: 'Toward the end of my tenure after the modules had been released, we wanted to add sharing features in. I created two basic user flows, one for sharing a static image and another for sharing a public user profile.',
  },
  {
    id: 'media-sharing-lod',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/sharing-lod-selection.png',
    alt: 'Sharing flow with level-of-detail selection',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-sharing-no-lod',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/sharing-no-lod-selection.png',
    alt: 'Sharing flow without level-of-detail selection',
    spaceBottom: true,
  },
  {
    id: 'gallery-share-screens',
    type: 'gallery',
    columns: 2,
    spaceBottom: true,
    items: [
      { src: '/assets/img/insitome/share-card-ancestry.png', alt: 'Shareable card for ancestry results' },
      { src: '/assets/img/insitome/share-card-lifestyle.png', alt: 'Shareable card for lifestyle results' },
      { src: '/assets/img/insitome/share-card-metabolism.png', alt: 'Shareable card for metabolism results' },
      { src: '/assets/img/insitome/share-card-nenderthal.png', alt: 'Shareable card for Neanderthal results' },
    ],
  },
  {
    id: 'wind-down-paragraph',
    type: 'paragraph',
    text: "After the holidays were over, I helped design a new marketing site but before construction was complete, Insitome parted ways with its product and engineering staff to put the company in maintenance mode. Helix shifted its focus to partnerships with healthcare systems and population genomics programs, and discontinued its consumer marketplace.",
  },
  {
    id: 'media-marketing-site',
    type: 'media',
    kind: 'image',
    src: '/assets/img/insitome/Marketing-Site@2x.jpg',
    alt: 'New Insitome marketing site design',
    spaceTop: true,
  },
]
