export const blocks = [
  {
    id: 'media-topper',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/unilease-topper.png',
    alt: 'Unilease homepage design',
    spaceBottom: true,
  },
  {
    id: 'intro-paragraph',
    type: 'paragraph',
    text: "Commercial real estate is an industry slow to adopt new ways of doing things. Brokers who are doing well for themselves have little incentive to change things, large firms even less so, and tenants are at the mercy of these gatekeepers' well-established processes. Landlords seem to be involved the least of anyone.",
  },
  {
    id: 'context-paragraph',
    type: 'paragraph',
    text: 'Unilease was created by a commercial real estate broker to streamline the way he did business, making it easier for both brokers and tenants. Part SaaS, part social network, I was brought in to help establish a design system, improve the existing user experience, and expand the toolset Unilease offered with the intent of it becoming a product available to all brokers and brokerages.',
  },
  {
    id: 'motivation-paragraph',
    type: 'paragraph',
    text: "A few things drew me to Unilease. First, my good friend and teammate from long ago worked there so I thought it would be great to work together. Second, I really liked founder and CEO Rob Marshall. But above all, the prospect of bridging the gap between two different types of users. I envisioned an experience that could be similar to gig economy products where the tech was ultimately a go-between for people looking for and offering services. Things didn't quite pan out the way I hoped, but I learned a ton.",
  },
  { id: 'heading-brand-marketing', type: 'heading', level: 2, text: 'Brand & Marketing' },
  {
    id: 'brand-goals-paragraph',
    type: 'paragraph',
    text: "The initial brand direction and logo were approached with several goals in mind differentiate from competitors in the CRE tech space; elevate the company to a more exclusive and luxurious level, but also avoid feeling too affectatious to brokers' clients. Above all else we were going for trustworthy, clean, energetic, and memorable.",
  },
  {
    id: 'media-type-exploration',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/type-exploration.png',
    alt: 'Typography exploration for the Unilease brand',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-mark-exploration',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/unilease-mark-exploration.png',
    alt: 'Logo mark exploration for Unilease',
    spaceBottom: true,
  },
  {
    id: 'media-patterns',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/unilease-patterns.png',
    alt: 'Pattern exploration for the Unilease brand',
    spaceBottom: true,
  },
  {
    id: 'mark-decision-paragraph',
    type: 'paragraph',
    text: "We settled on a simple mark without any visual reference to buildings, offices, or stores since commercial real estate can manifest in a variety of ways. This also harkened back to Unilease's old logo and felt like an improvement.",
  },
  {
    id: 'media-logo-final',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/logo-standard-black.svg',
    alt: 'The final Unilease logo mark',
  },
  {
    id: 'style-tiles-paragraph',
    type: 'paragraph',
    text: "In parallel to logo work I'd been picking at a few different style tiles to try to build a common visual vocabulary between everyone and suss out what made the most sense. This whole time I had been working on website concepts that incorporated the new branding. Once we'd settled on a direction, the look and feel of the site began to fall into place.",
  },
  {
    id: 'gallery-style-tiles',
    type: 'gallery',
    columns: 3,
    spaceTop: true,
    spaceBottom: true,
    items: [
      { src: '/assets/img/unilease/style-tile-a.png', alt: 'Style tile exploration A for the Unilease brand' },
      { src: '/assets/img/unilease/style-tile-b.png', alt: 'Style tile exploration B for the Unilease brand' },
      { src: '/assets/img/unilease/style-tile-c.png', alt: 'Style tile exploration C for the Unilease brand' },
    ],
  },
  {
    id: 'pivot-paragraph',
    type: 'paragraph',
    text: "Ironically right when we were close to deciding on a finalized brand direction, we realized a very similar product in the same space was using close to the same colors and typefaces. We decided to pivot a little. This was a foundation we were all comfortable starting from, and overall I'm happy with how it shook out.",
  },
  {
    id: 'media-marketing-site',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/marketing-site.png',
    alt: 'Unilease marketing site design',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-example-sign',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/example-sign.jpg',
    alt: 'Unilease branding applied to signage',
    spaceBottom: true,
  },
  {
    id: 'media-example-shirt',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/example-shirt.jpg',
    alt: 'Unilease branding applied to a t-shirt',
    spaceBottom: true,
  },
  {
    id: 'media-example-tote',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/example-tote.jpg',
    alt: 'Unilease branding applied to a tote bag',
    spaceBottom: true,
  },
  { id: 'heading-product', type: 'heading', level: 2, text: 'Product' },
  { id: 'heading-streamlining', type: 'heading', level: 3, text: 'Streamlining Archaic Processes' },
  {
    id: 'streamlining-intro-paragraph',
    type: 'paragraph',
    text: 'Unilease\'s biggest opportunity and most interesting challenge was modernizing old ways of doing things. One of these processes, surveying the market, had brokers creating files to describe leasable space their client was looking for, then playing a game of Go Fish with their network via phone and email. Some of the more complex work I did for Unilease involved this process.',
  },
  {
    id: 'cre-context-paragraph',
    type: 'paragraph',
    text: "If you're unfamiliar with commercial real state, it's easy to think of it from a residential point of view. Why not just make a search engine that lists available properties? Landlords could list their properties, tenants could find them, we eliminate the need for brokers, and that's it. But for a variety of reasons, it couldn't be this straightforward. For starters, landlords didn't have any incentive to change the way they did business, and brokers didn't want to make themselves obsolete. Brokers relied heavily on their personal and professional connections, and a large part of their job was being the purveyors of this closely guarded information of which sometimes they only gained street cred and favors for. Lastly there's a fairly large company that has an iron grip on commercial properties being listed online, and by becoming too much like it we risked alienating brokers and getting ourselves into major legal trouble.",
  },
  {
    id: 'constraints-paragraph',
    type: 'paragraph',
    text: 'All that to say, there are much better user experiences to solve this process, but the business strategy and circumstances of the space prevented them from being feasible.',
  },
  { id: 'heading-market-survey', type: 'heading', level: 4, text: '1. Creating the Market Survey' },
  {
    id: 'market-survey-paragraph',
    type: 'paragraph',
    text: 'This was simple enough, it\'s effectively an advanced search the broker sends out to their network to find available properties that might match what their client is wanting. If there were already properties that met those criteria which people in their network had listed within Unilease, we\'d let those people know and tell them to, otherwise we\'d just let them know their colleague was on the lookout for something matching that set of criteria. The most novel feature we had was the ability to draw boundaries on an interactive map.',
  },
  {
    id: 'media-market-survey',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/market-survey.png',
    alt: 'Interactive map for drawing market survey boundaries',
    modifier: 'compact',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'market-survey-speed-paragraph',
    type: 'paragraph',
    text: "The old method of doing this took 7–9 minutes. After my updates it took 1 minute, 16 seconds so 750% faster. So I'd say that's a win.",
  },
  { id: 'heading-submitting-properties', type: 'heading', level: 4, text: '2. Submitting Properties' },
  {
    id: 'submitting-properties-paragraph',
    type: 'paragraph',
    text: "This was a classic set of several data entry challenges. Too many fields, all uncategorized, no universal standardization for the data, lack of quality control, and don't get me started on the stuff that got uploaded for location photography. OCR wasn't an option, LLMs hadn't made their major debut, and our dev team was a single guy so it fell on me to design the best data entry experience I possibly could.",
  },
  {
    id: 'media-property-form',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/property-form-modal.png',
    alt: 'Property submission form modal',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-property',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/property.png',
    alt: 'Submitted property detail view',
    modifier: 'centered',
    spaceBottom: true,
  },
  { id: 'heading-analytics-comps-sharing', type: 'heading', level: 4, text: '3. Analytics, Comps, and Sharing' },
  {
    id: 'analytics-sharing-paragraph',
    type: 'paragraph',
    text: "Given the criteria the broker entered, we could generate analytics based on peer properties and lease data, which we decided could be a great upsell. Sharing presented an avalanche of complexity. Say a broker was putting together a market survey and they were a member of a team - a hierarchy comes into play where that person's manager should be able to see the survey as well. Then when the survey is shared with people on the tenant side, depending on how large of an organization the tenant is and how many people are involved in the decision process, the sharing of this private information quickly becomes less and less private. Our dev wanted to run the entire process using RBAC, but pigeonholing users into roles and asking admin users to categorize their team felt like a non-starter.",
  },
  {
    id: 'media-analytics',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/analytics.png',
    alt: 'Analytics view comparing peer properties and lease data',
    modifier: 'muted',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'research-difficulty-paragraph',
    type: 'paragraph',
    text: 'The big elephant in the room with all three of these tasks was recruiting for research proved really difficult. We had Fullstory and the broker founding Unilease got some of his colleagues to sign up, but I really wanted to have conversations with them and get the details from them. The majority of the user feedback we got was from our founder, Rob. We all wondered if perhaps more junior brokers just starting out might find the software more helpful.',
  },
  {
    id: 'heading-pricing-tiers',
    type: 'heading',
    level: 3,
    text: 'Business Strategy for Different Customer Tiers',
    spaceTop: true,
  },
  {
    id: 'pricing-tiers-paragraph',
    type: 'paragraph',
    text: "Creating pricing tiers for Unilease was one of those seemingly simple decisions that turned out to be anything but. We were debating whether to add a Team tier in addition to the Free and Pro tiers, and opinions were split on how to approach it. I decided to visualize the problem to help everyone see the implications more clearly. The flowchart mapped out how each approach would affect the user journey, show all the touchpoints where human intervention would be required, and highlighted what technical changes we'd need to make to the app to support each scenario. Although I can't remember exactly which direction we went, I can safely say the team arrived at a decision much faster.",
  },
  {
    id: 'media-pricing',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/unilease-pricing.png',
    alt: 'Flowchart mapping pricing tier decisions and their downstream effects',
    spaceTop: true,
    spaceBottom: true,
  },
  { id: 'heading-misc-screens', type: 'heading', level: 3, text: 'Other Misc. Screens' },
  {
    id: 'misc-screens-paragraph',
    type: 'paragraph',
    text: "There's a lot more that went on at Unilease than can fit in a single case study. I worked on a design system and the flowchart for an entire app. We pivoted strategy a few different times, rebuilt the app from scratch, switched platforms the marketing site was built on, hired freelance help, and shifted the roadmap a lot. I had a good time working with those guys and hope we're able to do it again sometime.",
  },
  {
    id: 'media-account-reg-flows',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/account-reg-flows.png',
    alt: 'Account registration flow diagrams',
    spaceTop: true,
    spaceBottom: true,
  },
  {
    id: 'media-dashsearch',
    type: 'media',
    kind: 'image',
    src: '/assets/img/unilease/dashsearch.png',
    alt: 'Dashboard search interface',
  },
]
